<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mtraces" nsURI="http://www.modelum.es/layoutGuesser/traces"
    nsPrefix="mtraces">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../../../lasser.sketchMM/src/lasser/sketchMM/sketch.ecore#//Widget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../../../guizmo.structureMM/src/guizmo/structureMM/structure.ecore#//GraphicalElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//Trace" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
